#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""C-BDD acceptance-criteria (.feature) deterministic assembler (WP-BDD).

Purpose:
    Takes the behavior-spec tables of a {PREFIX}-C draft — the `Status × Action
    matrix` of a policy WO, the `4-state interaction sequence` of a screen WO —
    and performs a **deterministic text transform** into Gherkin `.feature`
    acceptance criteria. No model involved — table cells are mapped verbatim to
    Given/When/Then, nothing is invented (render_assemble's BDD cousin).
    Drafts are read-only. Outputs must not be hand-edited (double authoring =
    SSoT collapse).

Mapping rules (deterministic):
    policy matrix cell (status Si, action Aj, value V≠blank)
      → Scenario: Given the system is in "Si" state / When "Aj" is attempted / Then result "V"
    screen 4-state row (Status / Condition / UI Display / User Action / Next Status)
      → Scenario: Given the screen is in "Status" (+condition) / When user "Action" / Then "UI" displayed
    `[[POL §X-Y]]` markers embedded in cells/rows and the frontmatter
    `referenced_policy` pin are preserved as Gherkin tags (@POL-§…) → policy
    traceability carries through to the dev team's tests.

Outputs:
    reports/bdd/{WO_ID}.feature                 (single)
    reports/bdd/{product}.all.feature           (--all)
    The header comment pins source_referenced_master →
      drift / bdd_coverage_scan compare stale/uncovered against it.

Usage:
    python bdd_assemble.py --hub-root <Hub> --product <p> [--wo <WO_ID>] [--all]

exit code: 0 success / 1 no input·fatal / 2 argument error
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
    except Exception:
        pass

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
POL_MARKER = re.compile(r"\[\[\s*POL\s*§?\s*([A-Za-z0-9][\w.\-()]*?)\s*\]\]")
# matrix table header detection: first cell contains "Status"+"Action" (or \ / × separator).
MATRIX_HEAD = re.compile(r"stat(?:us|e).*[\\×xX].*action|status\s*\\\s*action", re.I)
# column keywords for detecting the screen 4-state table.
STATE_COL = re.compile(r"^\s*status\s*$|^\s*state\s*$", re.I)
COND_COL = re.compile(r"condition", re.I)
UI_COL = re.compile(r"UI|display", re.I)
ACT_COL = re.compile(r"action|behavior", re.I)
NEXT_COL = re.compile(r"next|transition", re.I)
EMPTY_CELL = re.compile(r"^[\s\-–—]*$")

# required screen states — flow (idle/loading/success/error) and template
# (Empty/Loading/Loaded/Error) naming absorbed as synonym groups. SSoT shared
# with bdd_coverage_scan.
STATE_GROUPS = {
    "idle": re.compile(r"idle|empty|initial", re.I),
    "loading": re.compile(r"loading|in[- ]?progress", re.I),
    "success": re.compile(r"success|loaded|completed?|done", re.I),
    "error": re.compile(r"error|fail(?:ed|ure)?", re.I),
}
# 4-state subsection heading of the form '### 5-1. idle (initial entry)' (### or ####).
SUBHEAD = re.compile(r"^\s{0,3}#{3,4}\s+(.+?)\s*$")
TOPHEAD = re.compile(r"^\s{0,3}#{1,2}\s+")
# state N/A (not applicable) exemption markers — SSoT shared with bdd_coverage_scan.
NA = re.compile(r"N/?A\b|not\s+applicable|\bnone\b", re.I)
# detect WO instruction template (stub) generated by fanout — it is a work order,
# not a behavior spec. The real deliverable lives in a separate content draft
# (e.g. S01), so exclude stubs from BDD.
WO_STUB = re.compile(r"^#\s+Work Order:", re.M)


def is_wo_stub(body: str) -> bool:
    return bool(WO_STUB.search(body))


def _parse_frontmatter(text: str) -> tuple[dict, str]:
    m = FRONTMATTER.match(text)
    if not m:
        return {}, text
    fm: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        fm[k.strip()] = v.strip()
    return fm, text[m.end():]


def _refs(text: str) -> list[str]:
    """Extract [[POL §X-Y]] markers embedded in cell/row text as a §id list."""
    seen, out = set(), []
    for r in POL_MARKER.findall(text or ""):
        if r not in seen:
            seen.add(r)
            out.append(r)
    return out


def _tag(s: str) -> str:
    """Normalize for Gherkin tags — whitespace/separators to hyphens (no spaces in tags)."""
    s = re.sub(r"\s+", "-", str(s).strip())
    s = re.sub(r"[^\w§.\-]", "", s)
    return s.strip("-") or "x"


def extract_tables(body: str) -> list[tuple[list[str], list[list[str]]]]:
    """Extract markdown tables from the body as a list of (header cells, data rows)."""
    tables: list[tuple[list[str], list[list[str]]]] = []
    rows: list[list[str]] = []
    for raw in body.splitlines():
        line = raw.strip()
        if line.startswith("|") and line.endswith("|") and line.count("|") >= 2:
            cells = [c.strip() for c in line.strip("|").split("|")]
            rows.append(cells)
            continue
        if rows:
            tables.append(_finalize_table(rows))
            rows = []
    if rows:
        tables.append(_finalize_table(rows))
    return [t for t in tables if t[0]]


def _finalize_table(rows: list[list[str]]) -> tuple[list[str], list[list[str]]]:
    if not rows:
        return [], []
    header = rows[0]
    data = [r for r in rows[1:] if not all(re.fullmatch(r"[-:\s]*", c) for c in r)]
    return header, data


def find_matrix_table(tables) -> tuple[list[str], list[list[str]]] | None:
    for header, data in tables:
        if header and MATRIX_HEAD.search(header[0]):
            return header, data
        if header and ("Status" in header[0] and any(c[:1] == "A" or "Action" in c for c in header[1:])):
            return header, data
    return None


def find_state_table(tables) -> tuple[list[str], list[list[str]]] | None:
    for header, data in tables:
        if not header:
            continue
        # A screen 4-state table has a 'UI Display' or 'User Action' column. A
        # policy lifecycle table (Status|Definition|Entry Condition|Next Status —
        # no UI/action) must not be mistaken for a screen table, so UI/action
        # columns are required.
        if STATE_COL.search(header[0]) and any(
            UI_COL.search(c) or ACT_COL.search(c) for c in header[1:]
        ):
            return header, data
    return None


def policy_scenarios(table) -> list[dict]:
    """Matrix → list of scenario dicts, one per non-blank cell."""
    header, data = table
    actions = header[1:]
    out: list[dict] = []
    for row in data:
        if not row:
            continue
        state = row[0].strip()
        for j, cell in enumerate(row[1:]):
            if j >= len(actions):
                break
            val = cell.strip()
            if EMPTY_CELL.match(val):
                continue
            out.append({
                "state": state,
                "action": actions[j].strip(),
                "value": POL_MARKER.sub(lambda m: f"§{m.group(1)}", val).strip(),
                "refs": _refs(val + " " + state),
            })
    return out


def screen_scenarios(table) -> list[dict]:
    """4-state table → list of scenario dicts per row (column order agnostic, mapped by header name)."""
    header, data = table

    def idx(pat):
        for i, c in enumerate(header):
            if pat.search(c):
                return i
        return None

    i_state, i_cond, i_ui = 0, idx(COND_COL), idx(UI_COL)
    i_act, i_next = idx(ACT_COL), idx(NEXT_COL)
    out: list[dict] = []
    for row in data:
        if not row or not row[0].strip():
            continue

        def cell(i):
            return row[i].strip() if i is not None and i < len(row) else ""

        out.append({
            "state": row[0].strip(),
            "cond": cell(i_cond),
            "ui": cell(i_ui),
            "action": cell(i_act),
            "next": cell(i_next),
            "refs": _refs(" ".join(row)),
        })
    return out


def match_state_group(text: str) -> str | None:
    """Which required state group (idle/loading/success/error) the text matches — first match in dict order."""
    for name, pat in STATE_GROUPS.items():
        if pat.search(text or ""):
            return name
    return None


def extract_state_subsections(body: str) -> list[tuple[str, list]]:
    """'### N-x. {state}' style 4-state subsections → [(heading, [table, ...]), ...].

    Recognizes the project convention (cloud-calculator etc.) of writing each
    screen state as a subsection instead of the single standard table
    (`Status|Condition|UI|...`). Only subsections that match a state group and
    contain at least one table are returned (prose headings and unrelated
    section noise excluded)."""
    subs: list[tuple[str, list]] = []
    head: str | None = None
    buf: list[str] = []

    def flush():
        nonlocal head, buf
        if head is not None and match_state_group(head):
            tbls = extract_tables("\n".join(buf))
            if tbls:
                subs.append((head, tbls))
        head, buf = None, []

    for ln in body.splitlines():
        m = SUBHEAD.match(ln)
        if m:
            flush()
            head = m.group(1)
        elif TOPHEAD.match(ln):
            flush()  # entering a parent (## / #) section → close current subsection
        elif head is not None:
            buf.append(ln)
    flush()
    return subs


def state_group_coverage(body: str) -> dict[str, str]:
    """Per-state-group coverage verdict for the 4-state subsection format.

    Returns {group: 'table'|'na'}:
      - 'table': the state's subsection has a table (scenarios can be generated).
      - 'na'   : no table, but explicitly marked N/A ('N/A', 'not applicable',
                 'none' etc.) — e.g. error/loading of the S02 right panel:
                 static recomputation, no standalone error.
    A table always overrides an N/A marker. Groups that never appear are absent
    from the dict (= missing)."""
    cov: dict[str, str] = {}
    head: str | None = None
    buf: list[str] = []

    def flush():
        nonlocal head, buf
        if head:
            g = match_state_group(head)
            if g:
                txt = head + "\n" + "\n".join(buf)
                if extract_tables("\n".join(buf)):
                    cov[g] = "table"
                elif NA.search(txt) and cov.get(g) != "table":
                    cov[g] = "na"
        head, buf = None, []

    for ln in body.splitlines():
        m = SUBHEAD.match(ln)
        if m:
            flush()
            head = m.group(1)
        elif TOPHEAD.match(ln):
            flush()
        elif head is not None:
            buf.append(ln)
    flush()
    return cov


def screen_scenarios_from_subsections(body: str) -> list[dict]:
    """4-state subsection format → scenario dict list (same schema as screen_scenarios).

    Maps each state subsection's table rows deterministically (no cell invention):
      row[0] (item/trigger/error type) → cond, row[1:] (content/recovery/message) → ui.
    The state is the canonical group name (idle/loading/success/error) extracted
    from the heading."""
    out: list[dict] = []
    for head, tables in extract_state_subsections(body):
        grp = match_state_group(head)
        for _header, data in tables:
            for row in data:
                if not row or not any(c.strip() for c in row):
                    continue
                label = row[0].strip()
                content = " — ".join(c.strip() for c in row[1:] if c.strip())
                if not content and not label:
                    continue
                out.append({
                    "state": grp,
                    "cond": label,
                    "ui": content,
                    "action": "",
                    "next": "",
                    "refs": _refs(" ".join(row)),
                })
    return out


def _scenario_block(title: str, tags: list[str], steps: list[tuple[str, str]],
                    trail: str) -> str:
    tag_line = "  " + " ".join(f"@{t}" for t in tags) + "\n" if tags else ""
    body = "\n".join(f"    {kw:<6}{txt}" for kw, txt in steps)
    return f"{tag_line}  Scenario: {title}\n{body}\n    # trace: {trail}\n"


def _policy_blocks(scenarios: list[dict]) -> list[str]:
    blocks: list[str] = []
    for sc in scenarios:
        tags = [_tag(sc["state"]), _tag(sc["action"])] + [f"POL-{_tag(r)}" for r in sc["refs"]]
        steps = [
            ("Given", f'the system is in "{sc["state"]}" state'),
            ("When", f'"{sc["action"]}" is attempted'),
            ("Then", f'the result is "{sc["value"]}"'),
        ]
        trail = ", ".join(f"[[POL §{r}]]" for r in sc["refs"]) or "(no policy §refs)"
        blocks.append(_scenario_block(
            f'{sc["state"]} state, {sc["action"]} → {sc["value"]}', tags, steps, trail))
    return blocks


def _screen_blocks(scenarios: list[dict]) -> list[str]:
    blocks: list[str] = []
    for sc in scenarios:
        tags = [_tag(sc["state"])] + [f"POL-{_tag(r)}" for r in sc["refs"]]
        steps = [("Given", f'the screen is in "{sc["state"]}" state')]
        if sc["cond"]:
            steps.append(("And", f'the condition is "{sc["cond"]}"'))
        steps.append(("When", f'the user performs "{sc["action"]}"' if sc["action"]
                      else "the screen is displayed"))
        steps.append(("Then", f'"{sc["ui"]}" is displayed' if sc["ui"]
                      else "the defined UI is displayed"))
        if sc["next"]:
            steps.append(("And", f'the next state is "{sc["next"]}"'))
        trail = ", ".join(f"[[POL §{r}]]" for r in sc["refs"]) or "(no policy §refs)"
        blocks.append(_scenario_block(f'{sc["state"]} state interaction', tags, steps, trail))
    return blocks


def _feature_header(wo_id: str, fm: dict, kind: str, label: str) -> str:
    pin = fm.get("referenced_policy", "").strip()
    feat_tags = [f"source:{_tag(wo_id)}", f"type:{kind}"]
    if pin:
        feat_tags.append(f"POL:{_tag(pin)}")
    return (
        "# ⟦auto-generated — bdd_assemble.py (C-BDD, deterministic, no model)⟧\n"
        "# Do not edit directly (double authoring = SSoT collapse). Edit the source draft (/write·/flow·/write-cluster).\n"
        f"# source_doc_id: {wo_id}\n"
        f"# generated_at: {datetime.now().isoformat(timespec='seconds')}\n"
        f"# source_referenced_master: [{fm.get('referenced_master', '')}]\n"
        f"# referenced_policy: {pin or '-'}\n"
        "# language: en (Gherkin keywords and body in English — Cucumber/Behave default compatible)\n\n"
        + " ".join(f"@{t}" for t in feat_tags) + "\n"
        f"Feature: {wo_id} acceptance criteria ({label})\n"
        f"  Source: deterministic transform of the {label} table in drafts/{wo_id}.draft.md.\n"
        "  Re-run /bdd to resync when the draft changes.\n\n"
    )


def render_feature(wo_id: str, fm: dict, kind: str, scenarios: list[dict]) -> str:
    blocks = _policy_blocks(scenarios) if kind == "policy" else _screen_blocks(scenarios)
    label = "Status × Action" if kind == "policy" else "4-state interaction"
    header = _feature_header(wo_id, fm, kind, label)
    return header + "\n".join(blocks) + ("\n" if blocks else
        "  # ⚠️ no behavior spec table to convert — add a matrix/4-state table to the draft\n")


def render_cluster_feature(wo_id: str, fm: dict,
                           pol_scen: list[dict], scr_scen: list[dict]) -> str:
    """cluster_draft only — merge §1 policy matrix + §2 screen 4-state into one Feature."""
    header = _feature_header(wo_id, fm, "cluster", "policy matrix + screen 4-state")
    parts: list[str] = []
    if pol_scen:
        parts.append("  # ── §1 Policy Decisions (Status × Action) ──")
        parts.extend(_policy_blocks(pol_scen))
    if scr_scen:
        parts.append("  # ── §2 Screen Design (4-state) ──")
        parts.extend(_screen_blocks(scr_scen))
    if not parts:
        return header + "  # ⚠️ no §1 matrix / §2 4-state table to convert\n"
    return header + "\n".join(parts) + "\n"


def find_matrix_table_strict(tables) -> tuple[list[str], list[list[str]]] | None:
    """Strict matrix detection — only when the first header cell has the
    'Status × Action' form (MATRIX_HEAD). Prevents a cluster's §2 4-state (which
    has a 'User Action' column) from being mistaken for a matrix."""
    for header, data in tables:
        if header and MATRIX_HEAD.search(header[0]):
            return header, data
    return None


def assemble_one(text: str, wo_id: str) -> tuple[str, int, str]:
    """Draft body → (.feature string, scenario count, kind). Pure function (for tests).
    A cluster_draft extracts both the §1 matrix (policy) and §2 4-state (screen) and merges them."""
    fm, body = _parse_frontmatter(text)
    kind = (fm.get("type") or "").strip().lower()
    tables = extract_tables(body)
    if kind == "cluster_draft" or kind == "cluster":
        matrix = find_matrix_table_strict(tables)
        state = find_state_table(tables)
        pol = policy_scenarios(matrix) if matrix else []
        scr = screen_scenarios(state) if state else []
        return render_cluster_feature(wo_id, fm, pol, scr), len(pol) + len(scr), "cluster"
    if kind == "policy" or (not kind and find_matrix_table(tables)):
        kind = "policy"
        tbl = find_matrix_table(tables)
        scen = policy_scenarios(tbl) if tbl else []
    else:
        kind = "screen"
        tbl = find_state_table(tables)
        # standard single table first; fallback to the '### N-x. {state}' 4-state subsection format.
        scen = screen_scenarios(tbl) if tbl else screen_scenarios_from_subsections(body)
    return render_feature(wo_id, fm, kind, scen), len(scen), kind


def main() -> int:
    ap = argparse.ArgumentParser(description="C-BDD acceptance-criteria (.feature) deterministic assembly")
    ap.add_argument("--hub-root", required=True, type=Path)
    ap.add_argument("--product", required=True)
    ap.add_argument("--wo", default=None, help="single WO_ID (omit = all drafts)")
    ap.add_argument("--all", action="store_true", help="also generate {product}.all.feature")
    args = ap.parse_args()
    if not args.hub_root.is_dir():
        sys.stderr.write(f"hub-root not found: {args.hub_root}\n")
        return 2

    hub = args.hub_root
    proj = hub / "PROJECTS" / args.product
    drafts_dir = proj / "drafts"
    if not drafts_dir.is_dir():
        sys.stderr.write(f"drafts not found: {drafts_dir}\n")
        return 1

    targets = (
        [drafts_dir / f"{args.wo}.draft.md"] if args.wo
        else sorted(drafts_dir.glob("*.draft.md"))
    )
    targets = [t for t in targets if t.exists()]
    if not targets:
        sys.stderr.write("no target drafts\n")
        return 1

    out_dir = proj / "reports" / "bdd"
    out_dir.mkdir(parents=True, exist_ok=True)
    all_parts: list[str] = []
    total = 0
    skipped = 0
    for d in targets:
        wo = d.stem.replace(".draft", "")
        text = d.read_text(encoding="utf-8", errors="replace")
        if is_wo_stub(_parse_frontmatter(text)[1]):
            # WO instruction stub (not a behavior spec) — no feature generated, remove leftover stub feature.
            (out_dir / f"{wo}.feature").unlink(missing_ok=True)
            skipped += 1
            continue
        feature, n, kind = assemble_one(text, wo)
        (out_dir / f"{wo}.feature").write_text(feature, encoding="utf-8")
        all_parts.append(f"\n\n# ===== {wo} ({kind}) =====\n\n" + feature)
        total += n
        print(f"[bdd_assemble] {wo}.feature ← {kind} · {n} scenarios")

    if args.all and not args.wo:
        (out_dir / f"{args.product}.all.feature").write_text(
            "".join(all_parts), encoding="utf-8")
        print(f"[bdd_assemble] {args.product}.all.feature ({len(targets)} drafts)")

    print(f"[bdd_assemble] done — {len(targets) - skipped} drafts / {total} scenarios"
          + (f" ({skipped} WO stubs excluded)" if skipped else "")
          + f" → {out_dir.relative_to(hub)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
