#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""journey_emit — journey storyboard (reports/journey-*.md) → normalized journey contract.

There are two possible sources; the **most recently modified one** is parsed (read-only):
    reports/journey-latest.md            — auto-generated by journey_build.py (draft-edit hook)
    reports/journey-{YYYYMMDD-HHMM}.md   — manually generated by the /journey skill (actor filter, narrative enrichment)

[VIZ-LAYER ADAPTER]
    The sole consumer is the external extension (orange-pm-viz) — PrototypeView user journey board.
    Contract: docs/visual-interface/01-data-contract.md §5c.

Storyboard screen-line format (SKILL.md step 4):
    [{order}] {SCR-NNN} {screen name}  {status icon}
    + nested indented detail lines (진입 조건=entry / 핵심 행동=action / 전환=transition /
      이탈=exit / 목적=purpose — Korean field labels kept as a parsing contract with
      journey_build.py's output) — only present keys are added
Status icons: ✅ done / 📝 in-progress / 🔲 sketch / ⬜ not started
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import _emit_common as C

# [1] SCR-001 screen name  ✅   (icon optional)
_LINE = re.compile(r"^\[(\d+)\]\s+(\S+)\s+(.+?)\s*([✅📝🔲⬜])?\s*$")
_ICON_STATUS = {"✅": "done", "📝": "draft", "🔲": "sketch", "⬜": "todo"}

# Screen-line nested detail (SKILL.md step 4) — normalized to the keys the viz journey board displays.
# NOTE: the Korean labels below ("진입 조건:"=entry / "핵심 행동:"=action / "전환: → SCR-002 (condition)"=transition /
# "이탈: ✕ path"=exit / "목적:"=purpose) are kept as-is — they are a parsing contract with
# journey_build.py's generated output (out of scope for this translation pass).
_DETAIL_KEYS = {
    "진입 조건": "entry", "진입조건": "entry",
    "핵심 행동": "action", "핵심행동": "action",
    "전환": "transition",
    "이탈": "exit",
    "목적": "purpose",
    "REQ": "req",
}
_DETAIL_RE = re.compile(
    r"^(진입 ?조건|핵심 ?행동|전환|이탈|목적|REQ)\s*:\s*(.+)$"
)


def parse_storyboard(text: str) -> list[dict]:
    """Storyboard body → [{order, id, label, status, entry?, action?, …}].

    Extracts screen lines plus their nested indented detail lines (only
    present detail keys are added).
    """
    steps: list[dict] = []
    current: dict | None = None
    for raw in text.splitlines():
        line = raw.strip()
        m = _LINE.match(line)
        if m:
            order, sid, label, icon = m.group(1), m.group(2), m.group(3).strip(), m.group(4)
            # Only accept SCR-NNN / G2-... style (hyphenated identifier) as a
            # step — avoids false positives on summary lines/separators
            if not re.match(r"^[A-Za-z0-9]+-", sid):
                current = None
                continue
            current = {
                "order": int(order), "id": sid, "label": label,
                "status": _ICON_STATUS.get(icon or "", "unknown"),
            }
            steps.append(current)
            continue
        if current is not None and raw.startswith((" ", "\t")):
            dm = _DETAIL_RE.match(line)
            if dm:
                key = _DETAIL_KEYS.get(dm.group(1).replace(" ", ""), None) \
                    or _DETAIL_KEYS.get(dm.group(1))
                val = dm.group(2).strip().lstrip("→✕").strip()
                if key and val:
                    current[key] = val
        elif line and not raw.startswith((" ", "\t")):
            current = None  # End of screen block (e.g. a summary section)
    steps.sort(key=lambda s: s["order"])
    return steps


def _latest_journey(reports_dir: Path) -> Path | None:
    """The most recently modified journey-*.md — picks whichever of
    journey-latest.md (auto) and a timestamped file (manual) is actually
    newest (lexical filename order would always favor "latest", risking
    stale data)."""
    files = list(reports_dir.glob("journey-*.md"))
    if not files:
        return None
    try:
        return max(files, key=lambda p: p.stat().st_mtime)
    except OSError:
        return sorted(files)[-1]


def transform_journey(text: str, product: str = "") -> dict:
    return {"version": "", "product": product, "kind": "journey", "steps": parse_storyboard(text)}


def main(argv: list[str]) -> int:
    args = C.make_parser("journey").parse_args(argv)
    if args.from_fixture:
        return C.emit(C.load_fixture(args.from_fixture))
    if not (args.hub_root and args.product):
        sys.stderr.write("--hub-root, --product required\n")
        return 2
    rdir = C.product_dir(args.hub_root, args.product) / "reports"
    src = _latest_journey(rdir) if rdir.is_dir() else None
    if not src:
        sys.stderr.write(f"no journey-*.md found: {rdir}\n")
        return C.emit({"version": "empty", "product": args.product, "kind": "journey", "steps": []}) or 1
    return C.emit(transform_journey(src.read_text(encoding="utf-8"), args.product))


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
