#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract terms from imported documents + diff against the glossary → candidate queue (multi-tenant SaaS Phase 2).

Purpose:
    Relaxes the closed glossary (terms.yml requires pre-registration) into a
    "candidate queue + PM approval" flow. Extracts terms from an imported
    document (reuses build_a_index.extract_terms), diffs them against the
    existing glossary to classify as new/conflict (same term, different
    definition), and stages them into CONTEXT/glossary/term-candidates.yml.
    Does not modify terms.yml (the canonical source) directly — it's merged
    in separately after PM approval.

Usage:
    python term_extract.py --hub-root <Hub> --input X.md [--write-candidates]

exit code: 0 success / 1 no input / 2 argument error
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

from build_a_index import extract_terms

# Simple extraction of canonical_name/aliases from terms.yml / aliases.yml (no parser dependency).
_CANON = re.compile(r"-\s*canonical_name\s*:\s*(.+?)\s*$", re.MULTILINE)
_ALIASES = re.compile(r"aliases\s*:\s*\[(.*?)\]", re.MULTILINE)
_DEF = re.compile(r"definition\s*:\s*(.+?)\s*$", re.MULTILINE)


def _load_glossary(hub_root: Path) -> dict[str, str]:
    """Map of canonical_name → definition (empty '' if none). Aliases are also flattened in as keys."""
    out: dict[str, str] = {}
    terms_path = hub_root / "CONTEXT" / "glossary" / "terms.yml"
    if not terms_path.exists():
        return out
    text = terms_path.read_text(encoding="utf-8", errors="replace")
    # Matches canonical + definition per block (approximate) — based on line order.
    canon = None
    for line in text.splitlines():
        cm = _CANON.match(line.strip()) if line.strip().startswith("- canonical_name") else None
        if cm:
            canon = cm.group(1).strip().strip("'\"")
            out.setdefault(canon, "")
            continue
        dm = re.match(r"definition\s*:\s*(.+)$", line.strip())
        if dm and canon:
            out[canon] = dm.group(1).strip().strip("'\"")
            canon = None
    # Add alias keys that point to the same definition
    aliases_path = hub_root / "CONTEXT" / "glossary" / "aliases.yml"
    if aliases_path.exists():
        atext = aliases_path.read_text(encoding="utf-8", errors="replace")
        raw = canon2 = None
        for line in atext.splitlines():
            s = line.strip()
            rm = re.match(r'-\s*raw\s*:\s*"?(.+?)"?\s*$', s)
            cm = re.match(r'canonical_name\s*:\s*"?(.+?)"?\s*$', s)
            if rm:
                raw = rm.group(1)
            elif cm:
                canon2 = cm.group(1)
                if raw:
                    out.setdefault(raw, out.get(canon2, ""))
                    raw = None
    return out


def diff_terms(extracted: dict[str, dict], glossary: dict[str, str]) -> dict:
    """Diffs extracted terms against the glossary → {new, conflict, known}."""
    new: list[dict] = []
    conflict: list[dict] = []
    known: list[str] = []
    for term, meta in extracted.items():
        if term not in glossary:
            new.append({"term": term, "definition": meta["def"],
                        "file": meta["file"], "line": meta["line"]})
        else:
            existing = glossary[term]
            cand = meta["def"]
            # A conflict candidate if both definitions are non-empty and differ.
            if existing and cand and existing.strip() != cand.strip():
                conflict.append({"term": term, "existing": existing, "candidate": cand,
                                 "file": meta["file"], "line": meta["line"]})
            else:
                known.append(term)
    return {"new": new, "conflict": conflict, "known": known}


def _render_candidates_yaml(diff: dict, source: str) -> str:
    today = date.today().isoformat()
    lines = [
        "# term-candidates.yml — automatically extracted term candidates (staged before PM approval)",
        "# Auto-generated by term_extract.py. Manually merge into terms.yml after approval.",
        f"# Last updated: {today} · source: {source or '(unknown)'}",
        "",
        "candidates:",
    ]
    for item in diff["new"]:
        lines += [
            f"  - term: {item['term']}",
            f"    definition: {item['definition']}",
            f"    source: {source}",
            f"    location: \"{item['file']}:{item['line']}\"",
            "    status: pending",
        ]
    if diff["conflict"]:
        lines += ["", "conflicts:"]
        for item in diff["conflict"]:
            lines += [
                f"  - term: {item['term']}",
                f"    existing: {item['existing']}",
                f"    candidate: {item['candidate']}",
                f"    location: \"{item['file']}:{item['line']}\"",
                "    status: needs-review",
            ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Extract terms + diff against glossary → candidate queue")
    ap.add_argument("--hub-root", required=True, type=Path)
    ap.add_argument("--input", required=True, type=Path)
    ap.add_argument("--source", default="")
    ap.add_argument("--write-candidates", action="store_true",
                    help="Write to CONTEXT/glossary/term-candidates.yml")
    args = ap.parse_args()
    if not args.hub_root.is_dir():
        sys.stderr.write(f"hub-root not found: {args.hub_root}\n")
        return 2
    if not args.input.is_file():
        sys.stderr.write(f"input not found: {args.input}\n")
        return 1

    extracted = extract_terms(args.input.read_text(encoding="utf-8", errors="replace"),
                              str(args.input.name))
    glossary = _load_glossary(args.hub_root)
    diff = diff_terms(extracted, glossary)

    if args.write_candidates:
        out = args.hub_root / "CONTEXT" / "glossary" / "term-candidates.yml"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(_render_candidates_yaml(diff, args.source), encoding="utf-8")
        # Also append to the unknown-terms log (reuse existing asset)
        log = args.hub_root / "CONTEXT" / "glossary" / "unknown_terms.log"
        if diff["new"]:
            with log.open("a", encoding="utf-8") as fh:
                for item in diff["new"]:
                    fh.write(f"{date.today().isoformat()}\t{item['term']}\t{args.source}\n")
        print(f"[term_extract] wrote {out} "
              f"(new={len(diff['new'])}, conflict={len(diff['conflict'])})")
    else:
        print(f"[term_extract] {args.input.name}: "
              f"new={len(diff['new'])} conflict={len(diff['conflict'])} known={len(diff['known'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
